# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - oldrel
  - release
  - devel
  
 
#script:
#  - R CMD build . --compact-vignettes=gs+qpdf
#  - R CMD check *tar.gz --as-cran
r_github_packages:
  - JacintoCC/rNPBST
  - b0rxa/scmamp
bioc_packages:
  - Rgraphviz
  - graph
#after_success:
#  - tar -C .. -xf $PKG_TARBALL
#  - rm -rf RTest.Rcheck
#  - Rscript -e 'pkgdown::build_site()'